### PR TITLE
reformat Python clode with 'black'

### PR DESCRIPTION
**Pull request by mpontillo**

### CODE REVIEW

**Review by mamercad — APPROVED** [review]
🚢

**Comment by mamercad** [comment]
Strange, I ran `black` earlier on these ... do you use any flags?

**Comment by mpontillo** [comment]
Oh, that's interesting - I wonder if it'll revert my changes if you run it. I ran it with no flags, and I used the version of `black` on Bionic (I juts did `apt-get install black`; I wonder if there's a "better practice" we can use, like use a `Pipfile` and install it from there...?)

**Comment by mamercad** [comment]
> Oh, that's interesting - I wonder if it'll revert my changes if you run it. I ran it with no flags, and I used the version of `black` on Bionic (I juts did `apt-get install black`; I wonder if there's a "better practice" we can use, like use a `Pipfile` and install it from there...?)

Yep, we should probably `Pipfile` this thing, I'll wait :)

**Pull request merged**
